# Generated by Django 3.0.8 on 2020-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField()),
                ('publish_time', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_time', 'name'],
            },
        ),
    ]
