# Generated by Django 3.0.8 on 2020-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
