# Generated by Django 3.0.8 on 2020-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200714_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
