# Generated by Django 3.0.8 on 2020-07-17 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
