# Generated by Django 3.0.8 on 2020-07-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200717_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_charge',
            field=models.BooleanField(default=False),
        ),
    ]
