# Generated by Django 3.0.8 on 2020-07-27 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200718_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-update_time', 'name', 'author']},
        ),
        migrations.AddField(
            model_name='specifybook',
            name='borrow_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='specifybook',
            name='charge_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='specifybook',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author')},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_charge',
        ),
    ]
