# Generated by Django 3.0.8 on 2020-07-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_commentbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
