# Generated by Django 3.0.8 on 2020-07-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='book.Category'),
        ),
    ]
