# Generated by Django 3.0.8 on 2020-07-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200715_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
