# Generated by Django 3.0.8 on 2020-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200716_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='test',
            new_name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
